	CREATE TABLE TB_DM_INGREDIENTE(
  CD_INGREDIENTE NUMERIC(4) NOT NULL,
  NM_INGREDIENTE VARCHAR(60) NOT NULL,
  VR_INGREDIENTE NUMERIC(4,2) NOT NULL
);
ALTER TABLE TB_DM_INGREDIENTE ADD PRIMARY KEY (CD_INGREDIENTE);

CREATE TABLE TB_DM_SANDUICHE(
  CD_SANDUICHE NUMERIC(4) NOT NULL,
  NM_SANDUICHE VARCHAR(60) NOT NULL,
  DS_SANDUICHE VARCHAR(300) NOT NULL,
  VR_SANDUICHE NUMERIC(6,2)
);
ALTER TABLE TB_DM_SANDUICHE ADD PRIMARY KEY (CD_SANDUICHE);

CREATE SEQUENCE seq_tb_pedido;

CREATE TABLE TB_PEDIDO(
        CD_PEDIDO NUMERIC(9) DEFAULT NEXTVAL('seq_tb_pedido') NOT NULL,
        NU_CPF VARCHAR(11) NULL,
        NM_CLIENTE VARCHAR(60) NOT NULL,
        END_CLIENTE VARCHAR(300) NOT NULL,
        NU_TELEFONE VARCHAR(11),
        VR_TOTAL_PEDIDO NUMERIC(8,2),
        VR_TOTAL_DESCONTO NUMERIC(8,2),
        VR_COM_DESCONTO NUMERIC(8,2) NULL
      );
ALTER TABLE TB_PEDIDO ADD PRIMARY KEY (CD_PEDIDO);

CREATE SEQUENCE seq_tb_item_pedido;

CREATE TABLE TB_ITEM_PEDIDO(
        CD_ITEM_PEDIDO NUMERIC(9) DEFAULT NEXTVAL('seq_tb_item_pedido') NOT NULL,
        CD_PEDIDO NUMERIC(4) NOT NULL,
        CD_SANDUICHE NUMERIC(4),
	NM_SANDUICHE VARCHAR(60) NULL,
	DS_SANDUICHE VARCHAR(300) NULL,
        VR_SEM_DESCONTO NUMERIC(6,2),
        VR_COM_DESCONTO NUMERIC(6,2),
        VR_DESCONTO_TOTAL NUMERIC(6,2),
        VR_DESCONTO_PROMO_CARNE NUMERIC(6,2),
        VR_DESCONTO_PROMO_QUEIJO NUMERIC(6,2),
        VR_DESCONTO_PROMO_LIGHT NUMERIC(6,2),
        PROMO_CARNE NUMERIC(1) DEFAULT 0 NULL,
        PROMO_QUEIJO NUMERIC(1) DEFAULT 0 NULL,
        PROMO_LIGHT NUMERIC(1) DEFAULT 0 NULL
);

ALTER TABLE TB_ITEM_PEDIDO ADD PRIMARY KEY (CD_ITEM_PEDIDO);

ALTER TABLE TB_ITEM_PEDIDO
      ADD CONSTRAINT FK_PEDIDO
      FOREIGN KEY (CD_PEDIDO)
      REFERENCES TB_PEDIDO (CD_PEDIDO);
ALTER TABLE TB_ITEM_PEDIDO
      ADD CONSTRAINT FK_ITEM_SANDUICHE
      FOREIGN KEY (CD_SANDUICHE)
      REFERENCES TB_DM_SANDUICHE (CD_SANDUICHE);


CREATE SEQUENCE seq_tb_item_pedido_ingrediente;

CREATE TABLE TB_ITEM_PEDIDO_INGREDIENTE(
        CD_ITEM_PEDIDO_INGREDIENTE NUMERIC(9) DEFAULT NEXTVAL('seq_tb_item_pedido_ingrediente') NOT NULL,
        CD_ITEM_PEDIDO NUMERIC(9) NOT NULL,
        CD_INGREDIENTE NUMERIC(4) NOT NULL,
	NM_INGREDIENTE VARCHAR(60) NOT NULL,
        QTD_INGREDIENTE NUMERIC(3) NULL,
	VR_INGREDIENTE NUMERIC(4,2) NULL
);

ALTER TABLE TB_ITEM_PEDIDO_INGREDIENTE ADD PRIMARY KEY (CD_ITEM_PEDIDO_INGREDIENTE);

ALTER TABLE TB_ITEM_PEDIDO_INGREDIENTE
        ADD CONSTRAINT FK_ITEM_PEDIDO
        FOREIGN KEY (CD_ITEM_PEDIDO)
        REFERENCES TB_ITEM_PEDIDO (CD_ITEM_PEDIDO);

ALTER TABLE TB_ITEM_PEDIDO_INGREDIENTE
        ADD CONSTRAINT FK_INGREDIENTE
        FOREIGN KEY (CD_INGREDIENTE)
        REFERENCES TB_DM_INGREDIENTE (CD_INGREDIENTE);

ALTER TABLE TB_ITEM_PEDIDO_INGREDIENTE
  ADD COLUMN VR_SEM_DESCONTO NUMERIC(6,2),
  ADD COLUMN VR_DESCONTO NUMERIC(6,2),
  ADD COLUMN VR_COM_DESCONTO NUMERIC(6,2),
  ADD COLUMN QTD_INGREDIENTE_PGTO NUMERIC(3);

ALTER TABLE TB_ITEM_PEDIDO_INGREDIENTE
  ADD COLUMN PROMO_CARNE NUMERIC(1) DEFAULT 0 NULL,
  ADD COLUMN PROMO_QUEIJO NUMERIC(1) DEFAULT 0 NULL;

CREATE TABLE public.tb_sanduiche_ingrediente (
	cd_sanduiche numeric(4) NULL,
	cd_ingrediente numeric(4) NULL,
	CONSTRAINT fk_ingrediente FOREIGN KEY (cd_ingrediente) REFERENCES tb_dm_ingrediente(cd_ingrediente),
	CONSTRAINT fk_sanduiche FOREIGN KEY (cd_sanduiche) REFERENCES tb_dm_sanduiche(cd_sanduiche)
)
