version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: foodstore
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data
      - ./postgresql/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
